# Generated by Django 5.1.2 on 2024-10-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libri', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libri',
            name='data_pubblicazione',
            field=models.CharField(max_length=10, verbose_name='Data di pubblicazione'),
        ),
    ]
