# Generated by Django 5.1.1 on 2024-10-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libri', '0003_remove_libri_data_pubblicazione_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libri',
            name='anno_pubblicazione',
            field=models.IntegerField(max_length=10, verbose_name='Anno di pubblicazione'),
        ),
    ]
