# Generated by Django 5.1.1 on 2024-10-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libri', '0005_alter_libri_anno_pubblicazione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libri',
            name='anno_pubblicazione',
            field=models.IntegerField(blank=True, null=True, verbose_name='Anno di pubblicazione'),
        ),
    ]
