# Generated by Django 5.1.1 on 2024-10-22 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libri', '0006_alter_libri_anno_pubblicazione'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='libri',
            unique_together={('titolo', 'autore')},
        ),
    ]
